# Site settings
title: Wickedy Woo
header-img: img/home-bg.jpg
email: velin.br.vangelov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wickerdy Wackedy Woo ...
baseurl: ""
url: "http://kryptikko.github.io" # the base hostname & protocol for your site
twitter_username: kryptikko
github_username:  kryptikko
linkedin_id:  269414826
# facebook_username:  velin.vangelov

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
